"""Workspace-config management commands: ``new``, ``copy``, ``delete``, ``implode``.

Mirrors tmuxinator's ``new``/``copy``/``delete``/``implode`` subcommands
(cli.rb:78-457). Implemented in a single module to keep the four
commands' shared file-IO patterns close together.
"""

from __future__ import annotations

import argparse
import logging
import os
import pathlib
import shutil
import subprocess
import sys
import typing as t

from tmuxp._internal.private_path import PrivatePath
from tmuxp.workspace.finders import find_workspace_file, get_workspace_dir

from ._colors import Colors, build_description, get_color_mode
from .utils import tmuxp_echo

logger = logging.getLogger(__name__)

if t.TYPE_CHECKING:
    from typing import TypeAlias

    CLIColorModeLiteral: TypeAlias = t.Literal["auto", "always", "never"]


_NEW_TEMPLATE = """# {name}.yaml — generated by `tmuxp new {name}`
session_name: {name}
windows:
- window_name: editor
  panes:
  - shell_command:
    -
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _config_path(name: str) -> pathlib.Path:
    """Return the canonical workspace file path for ``name`` in the user's dir."""
    return pathlib.Path(get_workspace_dir()) / f"{name}.yaml"


def _ensure_dir(path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _open_in_editor(path: pathlib.Path) -> None:
    editor = os.environ.get("EDITOR", "vim")
    subprocess.call([editor, str(path)])


def _confirm(prompt: str, *, default_no: bool = True) -> bool:
    """Read y/n from stdin; on EOF (no TTY) return ``not default_no``."""
    suffix = " [y/N] " if default_no else " [Y/n] "
    try:
        answer = input(prompt + suffix).strip().lower()
    except EOFError:
        return not default_no
    if not answer:
        return not default_no
    return answer in {"y", "yes"}


# ---------------------------------------------------------------------------
# new
# ---------------------------------------------------------------------------


NEW_DESCRIPTION = build_description(
    "Create a new tmuxp workspace file in the user's workspace directory.",
    ((None, ["tmuxp new myproject"]),),
)


class CLINewNamespace(argparse.Namespace):
    """Typed namespace for ``tmuxp new``."""

    name: str
    color: CLIColorModeLiteral | None


def create_new_subparser(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    """Augment :class:`argparse.ArgumentParser` for ``tmuxp new``."""
    parser.add_argument("name", help="config name (without .yaml extension)")
    return parser


def command_new(
    args: CLINewNamespace, parser: argparse.ArgumentParser | None = None
) -> None:
    """Entry point for ``tmuxp new``."""
    colors = Colors(get_color_mode(args.color))
    target = _config_path(args.name)
    _ensure_dir(target)
    if not target.exists():
        target.write_text(_NEW_TEMPLATE.format(name=args.name), encoding="utf-8")
        tmuxp_echo(colors.muted("Created ") + colors.info(str(PrivatePath(target))))
    _open_in_editor(target)


# ---------------------------------------------------------------------------
# copy
# ---------------------------------------------------------------------------


COPY_DESCRIPTION = build_description(
    "Copy an existing workspace file to a new name and open it for editing.",
    ((None, ["tmuxp copy myproject myproject-staging"]),),
)


class CLICopyNamespace(argparse.Namespace):
    """Typed namespace for ``tmuxp copy``."""

    src: str
    dst: str
    answer_yes: bool
    color: CLIColorModeLiteral | None


def create_copy_subparser(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    """Augment :class:`argparse.ArgumentParser` for ``tmuxp copy``."""
    parser.add_argument("src", help="source config name or path")
    parser.add_argument("dst", help="destination config name (without extension)")
    parser.add_argument(
        "-y",
        "--yes",
        dest="answer_yes",
        action="store_true",
        help="skip overwrite confirmation",
    )
    return parser


def command_copy(
    args: CLICopyNamespace, parser: argparse.ArgumentParser | None = None
) -> None:
    """Entry point for ``tmuxp copy``."""
    colors = Colors(get_color_mode(args.color))
    src_path = pathlib.Path(find_workspace_file(args.src))
    dst_path = _config_path(args.dst)
    _ensure_dir(dst_path)
    if (
        dst_path.exists()
        and not args.answer_yes
        and not _confirm(colors.warning(f"Overwrite {PrivatePath(dst_path)}?"))
    ):
        tmuxp_echo(colors.muted("Aborted."))
        return
    shutil.copyfile(src_path, dst_path)
    tmuxp_echo(
        colors.muted("Copied ")
        + colors.info(str(PrivatePath(src_path)))
        + colors.muted(" -> ")
        + colors.info(str(PrivatePath(dst_path))),
    )
    _open_in_editor(dst_path)


# ---------------------------------------------------------------------------
# delete
# ---------------------------------------------------------------------------


DELETE_DESCRIPTION = build_description(
    "Delete one or more workspace config files (with confirmation).",
    ((None, ["tmuxp delete myproject", "tmuxp delete proj1 proj2"]),),
)


class CLIDeleteNamespace(argparse.Namespace):
    """Typed namespace for ``tmuxp delete``."""

    names: list[str]
    answer_yes: bool
    color: CLIColorModeLiteral | None


def create_delete_subparser(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    """Augment :class:`argparse.ArgumentParser` for ``tmuxp delete``."""
    parser.add_argument("names", nargs="+", help="config name(s) to delete")
    parser.add_argument(
        "-y",
        "--yes",
        dest="answer_yes",
        action="store_true",
        help="skip per-config confirmation",
    )
    return parser


def command_delete(
    args: CLIDeleteNamespace, parser: argparse.ArgumentParser | None = None
) -> None:
    """Entry point for ``tmuxp delete``."""
    colors = Colors(get_color_mode(args.color))
    for name in args.names:
        try:
            path = pathlib.Path(find_workspace_file(name))
        except Exception:
            tmuxp_echo(colors.error(f"Not found: {name}"))
            continue
        if not args.answer_yes and not _confirm(
            colors.warning(f"Delete {PrivatePath(path)}?"),
        ):
            tmuxp_echo(colors.muted(f"Skipped {PrivatePath(path)}"))
            continue
        path.unlink()
        tmuxp_echo(colors.muted("Deleted ") + colors.info(str(PrivatePath(path))))


# ---------------------------------------------------------------------------
# implode
# ---------------------------------------------------------------------------


IMPLODE_DESCRIPTION = build_description(
    "Delete ALL workspace config files in every tmuxp workspace directory.",
    ((None, ["tmuxp implode"]),),
)


class CLIImplodeNamespace(argparse.Namespace):
    """Typed namespace for ``tmuxp implode``."""

    answer_yes: bool
    color: CLIColorModeLiteral | None


def create_implode_subparser(
    parser: argparse.ArgumentParser,
) -> argparse.ArgumentParser:
    """Augment :class:`argparse.ArgumentParser` for ``tmuxp implode``."""
    parser.add_argument(
        "-y",
        "--yes",
        dest="answer_yes",
        action="store_true",
        help="skip the global confirmation prompt",
    )
    return parser


def _implode_dirs() -> list[pathlib.Path]:
    """Return existing tmuxp config directories worth removing."""
    candidates = [
        pathlib.Path(os.path.expanduser("~/.tmuxp")),
        pathlib.Path(os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")))
        / "tmuxp",
    ]
    return [p for p in candidates if p.exists() and p.is_dir()]


def command_implode(
    args: CLIImplodeNamespace, parser: argparse.ArgumentParser | None = None
) -> None:
    """Entry point for ``tmuxp implode``."""
    colors = Colors(get_color_mode(args.color))
    dirs = _implode_dirs()
    if not dirs:
        tmuxp_echo(colors.muted("No tmuxp config directories found."))
        return
    if not args.answer_yes and not _confirm(
        colors.error(f"Delete ALL configs in: {', '.join(str(d) for d in dirs)}?"),
    ):
        tmuxp_echo(colors.muted("Aborted."))
        return
    for d in dirs:
        shutil.rmtree(d)
        tmuxp_echo(colors.muted("Removed ") + colors.info(str(PrivatePath(d))))


# Silence unused-import warnings on platforms where `sys` isn't directly needed
# at runtime (kept for future stdin-detection extensions).
_ = sys
